### ISSUE TITLE
importation issue

### ISSUE THREAD

**Issue by NK-Inomine** [mr-teslaa/Taqwa-EDMS#31]
@mr-teslaa Hello am leraning flask with this project and am facing an issue that am struggling with, that is **ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous** I googled it, also checked on youtube but still couldn't solve it I will appreciate if you can explain me why am getting this error and how to fix. Thanks

**Comment by mr-teslaa** [comment]
@NK-Inomine, it's because they have removed that module at itsdangerous updated version.

However, use older version to get rid of this error. Install `pip install itsdangerous==1.1.0` will resolve that.
Cheers 🥂

**Comment by NK-Inomine** [comment]
Thanks

Le lun. 11 déc. 2023 à 11:27, Hossain Foysal ***@***.***> a
écrit :

**Comment by NK-Inomine** [comment]
Am really sorry for asking many questions but I got another issue that is :  from watchdog.events import EVENT_TYPE_OPENED
ImportError: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events'. you can see when debugging mode is on in the terminal and going through the port 5000 I got  : 

 Hmmm… can't reach this page
 127.0.0.1 refused to connect.
Try:

Search the web for [127 0 0 1](https://www.bing.com/search?form=ANLKDR&q=127%200%200%201)
Checking the connection


I tried to go on youtube and searching on google but still don't get it, I tried what they said but still nothing

**Comment by mr-teslaa** [comment]
@NK-Inomine 
Can you mention the file name where are you encountering this error?
