### ISSUE TITLE
Create a successful admission form

### ISSUE THREAD

**Issue by mr-teslaa** [mr-teslaa/Taqwa-EDMS#8]

**Comment by fmelihh** [comment]
Closed

**Comment by FROST03-cyber** [comment]
How does one access the website i tried admin as username it didn't work kindly respond soon

**Comment by FROST03-cyber** [comment]
Thanks so much...one last question if i were to represent this project(hope
you are okay with its just for school work)if am asked why we export the
flask_run

**Comment by fmelihh** [comment]
I would be very happy to have the project published somewhere, but I did
not understand the second question.Can you explain a little more clearly ?

**Comment by FROST03-cyber** [comment]
In the readme.md there are instructions on how to use the system ..am using
linux thus we use the export functions like export
flask_ENV=flask_development or something like that .....so if i am asked
why we export those fuctions what should i say or how should i explain??

**Comment by fmelihh** [comment]
The reason we export environment variables is because it gives us speed.If
you don't add it, you have to write long.I don't think you need to explain
it.

**Comment by mr-teslaa** [comment]
> .

@FROST03-cyber, you should say 
there is 2 mode Production what we are using when the website is published on a server. another mode is Development what we need to enable while we are developing the project. If we didn't enable the `export FLASK_ENV=development` or `export FLASK_DEBUG=1` we will not see the where and which line of our code is causing the error. we will just see **500 Internal Server Error**, by developing mode we are telling the flask server to show us the error message and where exactly the error is occurring. 

Cheers 🥂
